title:
  ru: Славян&shy;ская инфор&shy;матика
  en: Slavo&shy;nic Compu&shy;ting

keywords:
  ru: "церковнославянский язык, церковно-славянский язык, старославянский язык, церковнославянский шрифт, старославянский шрифт, церковно-славянский шрифт, славянский шрифт, Юникод, славянский Юникод, церковнославянская типографика"
  en: "Church Slavic, Church Slavonic, Old Church Slavonic, Old Slavonic, Old Bulgarian, Old Church Slavic, unicode, Slavonic unicode, fonts, Slavonic fonts, Slavic fonts, keyboard layout, hyphenation, transliteration, Glagolitic, Glagolica, Cyrillic fonts, Glagolitic fonts, Znamenny notation, Znamenny fonts, OpenType, TrueType, Graphite, SIL Graphite, private use area"

authors:
  ru: Александр Андреев, Михаил Крутиков
  en: Aleksandr Andreev, Mike Kroutikov

google_analytics: "UA-12187460-3"
 
markdown:
  kramdown
